import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import ContactForm from "@/components/ContactForm";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
  landing: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased overflow-x-hidden`}>
        {props.children}
        {props.landing}
        <ContactForm />
        <Footer />
      </body>
    </html>
  );
}
